### ISSUE TITLE
Slight issue with bout.env

### ISSUE THREAD

**Issue by PoloidalLloyd** [mikekryjak/bout-build-scripts#2]
There's a slight issue loading the module dependencies on Viking, I believe the data structure may have changed slight, and I had to add prefix's to the modules, such as "numlib/OpenBLAS/0.3.15-GCC-10.3.0" instead of just "OpenBLAS/0.3.15-GCC-10.3.0". 

I've attached my 'corrected' version that seems to operate as intended as a text file.
[bout .txt](https://github.com/mikekryjak/bout-build-scripts/files/11689693/bout.txt)

All the best,

Lloyd

**Comment by mikekryjak** [comment]
That's odd, I've used this as recently as this week with no issue. Will take a look, thanks!

**Comment by PoloidalLloyd** [comment]
It could just be me!

**Comment by PoloidalLloyd** [comment]
I realise I checked out the wrong branch! Please ignore.
